<template>
  <div>
    <section class="bg-primary-950 py-14 text-white sm:py-20">
      <div class="container-page grid items-center gap-10 lg:grid-cols-[1.05fr_.95fr]">
        <div><p class="text-sm font-semibold uppercase tracking-[0.2em] text-primary-200">Contact Lexshield</p><h1 class="mt-4 text-4xl font-extrabold sm:text-5xl">Let’s find the right property for you</h1><p class="mt-5 max-w-2xl text-lg leading-8 text-primary-100">Tell us what you are looking for and a Lexshield property advisor will help you understand current availability, pricing, payment plans and inspection options.</p><ul class="mt-7 space-y-3 text-primary-100"><li v-for="item in trustPoints" :key="item" class="flex items-start gap-3"><CheckCircle class="mt-0.5 h-5 w-5 shrink-0 text-secondary-300"/><span>{{ item }}</span></li></ul></div>
        <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2"><a :href="phoneLink" class="rounded-2xl border border-white/15 bg-white/10 p-5 backdrop-blur transition hover:bg-white/15" @click="track('phone_click')"><Phone class="h-7 w-7 text-secondary-300"/><span class="mt-4 block text-sm text-primary-200">Call us now</span><strong class="mt-1 block text-lg">{{ phone }}</strong></a><a :href="whatsappLink" target="_blank" rel="noopener" class="rounded-2xl bg-[#25D366] p-5 transition hover:bg-[#1daf54]" @click="track('whatsapp_click')"><MessageCircle class="h-7 w-7"/><span class="mt-4 block text-sm text-white/80">Fastest response</span><strong class="mt-1 block text-lg">Chat on WhatsApp</strong></a></div>
      </div>
    </section>

    <section class="section bg-neutral-50"><div class="container-page grid items-start gap-8 lg:grid-cols-[1fr_1.45fr] lg:gap-12">
      <aside class="space-y-5 lg:sticky lg:top-28"><div><p class="text-sm font-semibold uppercase tracking-wider text-primary-700">Get in touch</p><h2 class="mt-2 text-3xl text-neutral-900">How can we help?</h2><p class="mt-3 leading-7 text-neutral-600">Choose the channel that works for you, or send the short form and let our team call you.</p></div><div class="card divide-y"><a :href="phoneLink" class="flex gap-4 p-5 hover:bg-primary-50" @click="track('phone_click')"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary-100 text-primary-700"><Phone class="h-5 w-5"/></span><span><strong class="block text-neutral-900">Phone</strong><span class="mt-1 block text-sm text-neutral-600">{{ phone }}</span></span></a><a :href="`mailto:${email}`" class="flex gap-4 p-5 hover:bg-primary-50"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary-100 text-primary-700"><Mail class="h-5 w-5"/></span><span class="min-w-0"><strong class="block text-neutral-900">Email</strong><span class="mt-1 block break-all text-sm text-neutral-600">{{ email }}</span></span></a><div class="flex gap-4 p-5"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary-100 text-primary-700"><Clock3 class="h-5 w-5"/></span><span><strong class="block text-neutral-900">Office hours</strong><span class="mt-1 block text-sm text-neutral-600">Monday–Saturday, 8am–6pm</span></span></div></div><div class="rounded-xl bg-secondary-50 p-5 text-sm leading-6 text-secondary-900 ring-1 ring-secondary-100"><strong>Planning a site visit?</strong><p class="mt-1">Use our inspection form to select a property, plot option and preferred date.</p><NuxtLink to="/book-inspection" class="mt-3 inline-flex font-semibold underline">Book Site Inspection →</NuxtLink></div></aside>

      <div class="card p-6 sm:p-8"><div v-if="submitted" class="flex min-h-[480px] flex-col items-center justify-center text-center"><span class="flex h-16 w-16 items-center justify-center rounded-full bg-success-100 text-success-700"><CheckCircle class="h-9 w-9"/></span><h2 class="mt-5 text-3xl text-neutral-900">Thank you, {{ form.name }}!</h2><p class="mt-3 max-w-md leading-7 text-neutral-600">Your enquiry has been received. A Lexshield advisor will contact you using the details provided.</p><div class="mt-6 flex flex-wrap justify-center gap-3"><a :href="whatsappLink" target="_blank" rel="noopener" class="btn-whatsapp">Continue on WhatsApp</a><button class="btn-outline" @click="resetForm">Send Another Enquiry</button></div></div>
        <template v-else><div><p class="text-sm font-semibold uppercase tracking-wider text-primary-700">Request a callback</p><h2 class="mt-2 text-3xl text-neutral-900">Tell us what you need</h2><p class="mt-2 text-sm text-neutral-600">Fields marked * are required. We’ll only use your details to respond to this enquiry.</p></div><form class="mt-7 space-y-5" @submit.prevent="submit"><div class="grid gap-5 sm:grid-cols-2"><div><label class="label" for="contact-name">Full name *</label><input id="contact-name" v-model.trim="form.name" class="input" autocomplete="name" required placeholder="Your full name" /></div><div><label class="label" for="contact-phone">Phone / WhatsApp *</label><input id="contact-phone" v-model.trim="form.phone" class="input" type="tel" inputmode="tel" autocomplete="tel" required placeholder="e.g. 0801 234 5678" /></div><div><label class="label" for="contact-email">Email address</label><input id="contact-email" v-model.trim="form.email" class="input" type="email" autocomplete="email" placeholder="you@example.com" /></div><div><label class="label" for="contact-reason">I want to… *</label><select id="contact-reason" v-model="form.reason" class="input" required><option disabled value="">Select an option</option><option>Buy land</option><option>Ask about payment plans</option><option>Book a site inspection</option><option>Discuss a commercial plot</option><option>Make a general enquiry</option></select></div></div><div><label class="label" for="contact-property">Property of interest</label><select id="contact-property" v-model="form.property_id" class="input"><option value="">I’m not sure yet</option><option v-for="property in properties" :key="property.id" :value="property.id">{{ property.name }} — {{ property.city }}</option></select></div><div><label class="label" for="contact-message">How can we help?</label><textarea id="contact-message" v-model.trim="form.message" class="input min-h-32 resize-y" placeholder="Tell us your preferred location, budget, plot size or questions." /></div><label class="flex items-start gap-3 text-sm leading-6 text-neutral-600"><input v-model="form.consent" type="checkbox" class="mt-1 h-4 w-4 rounded border-neutral-300 text-primary-700 focus:ring-primary-500" required /><span>I agree that Lexshield may contact me about this enquiry. *</span></label><p v-if="errorMessage" role="alert" class="rounded-lg bg-error-50 p-3 text-sm text-error-800">{{ errorMessage }}</p><button class="btn-primary w-full py-3.5" :disabled="submitting"><LoaderCircle v-if="submitting" class="h-5 w-5 animate-spin"/>{{ submitting ? 'Sending your enquiry…' : 'Send Enquiry' }}</button><p class="text-center text-xs text-neutral-500"><LockKeyhole class="mr-1 inline h-3.5 w-3.5"/>Your information is sent securely and is not displayed publicly.</p></form></template>
      </div>
    </div></section>

    <section class="section"><div class="container-page max-w-3xl"><div class="text-center"><p class="text-sm font-semibold uppercase tracking-wider text-primary-700">Before you contact us</p><h2 class="mt-2 text-3xl">Frequently Asked Questions</h2></div><div class="mt-8 divide-y rounded-2xl border border-neutral-200 bg-white px-5 sm:px-7"><details v-for="faq in faqs" :key="faq.question" class="group py-5"><summary class="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold text-neutral-900"><span>{{ faq.question }}</span><Plus class="h-5 w-5 shrink-0 transition group-open:rotate-45"/></summary><p class="mt-3 pr-8 text-sm leading-7 text-neutral-600">{{ faq.answer }}</p></details></div></div></section>
  </div>
</template>

<script setup lang="ts">
import { CheckCircle, Clock3, LoaderCircle, LockKeyhole, Mail, MessageCircle, Phone, Plus } from 'lucide-vue-next'
const config=useRuntimeConfig();const route=useRoute();const {list}=useProperties();const {buildTelLink,number:phone}=usePhone();const {buildUrl}=useWhatsApp();const phoneLink=computed(()=>buildTelLink());const whatsappLink=computed(()=>buildUrl());const email=computed(()=>config.public.email);const {data:properties}=useAsyncData('contact-properties',()=>list());const submitting=ref(false);const submitted=ref(false);const errorMessage=ref('');
const form=reactive({name:'',phone:'',email:'',reason:'',property_id:'',message:'',consent:false});const selectedProperty=computed(()=>properties.value?.find(item=>item.id===form.property_id));const trustPoints=['Clear guidance on current property options','Transparent pricing and payment-plan information','Site inspections available for active properties'];const faqs=[{question:'Can I book a physical site inspection?',answer:'Yes. Select “Book Site Inspection” to choose an active property and preferred date. Our team will contact you to confirm the visit.'},{question:'Can I ask about payment plans before choosing a property?',answer:'Yes. Tell us your preferred location and budget, and an advisor can explain the currently published options.'},{question:'What should I prepare before buying land?',answer:'Review the property information, inspect the site, confirm current pricing and documentation, and complete appropriate independent due diligence before making payment.'},{question:'How quickly will someone respond?',answer:'WhatsApp is usually the fastest channel during office hours. Form enquiries are sent to the sales lead system for follow-up.'}];
function attribution(){const query=route.query;return{utm_source:String(query.utm_source||'')||null,utm_medium:String(query.utm_medium||'')||null,utm_campaign:String(query.utm_campaign||'')||null,utm_content:String(query.utm_content||'')||null,page_url:import.meta.client?window.location.href:null,referrer:import.meta.client?document.referrer||null:null}}
function track(event:string){if(import.meta.client)window.dataLayer?.push({event,page:'contact',property_name:selectedProperty.value?.name})}
async function submit(){errorMessage.value='';submitting.value=true;try{const property=selectedProperty.value;const message=[`Enquiry type: ${form.reason}`,form.message].filter(Boolean).join('\n\n');const {error}=await useSupabase().from('leads').insert({name:form.name,phone:form.phone,email:form.email||null,message,property_id:property?.id||null,property_name:property?.name||null,property_location:property?.location_name||null,property_price:property?.price_display||null,source:'contact_page',...attribution()});if(error)throw error;submitted.value=true;track('lead_submitted')}catch(error){console.error(error);errorMessage.value='We could not send your enquiry right now. Please call us or continue on WhatsApp.'}finally{submitting.value=false}}
function resetForm(){Object.assign(form,{name:'',phone:'',email:'',reason:'',property_id:'',message:'',consent:false});submitted.value=false}
const canonical=`${config.public.siteUrl.replace(/\/$/,'')}/contact`;useSeoMeta({title:'Contact Lexshield Properties | Property Enquiries Nigeria',description:'Contact Lexshield Properties about available land, current prices, flexible payment plans and site inspections in Nigeria.',ogTitle:'Contact Lexshield Properties',ogDescription:'Speak with a Lexshield property advisor about available properties, payment plans and site inspections.',ogType:'website',ogUrl:canonical});useHead({link:[{rel:'canonical',href:canonical}]})
</script>
