<template>
  <div v-if="property">
    <section class="bg-primary-950 py-14 text-white"><div class="container-page">
      <div class="flex flex-wrap gap-2"><span class="badge bg-success-500 text-white">NOW SELLING</span><span v-if="property.price_inclusive" class="badge bg-secondary-500 text-white">ALL PRICES INCLUSIVE</span></div>
      <h1 class="mt-5 max-w-4xl text-4xl sm:text-5xl">{{ pageHeading }}</h1><p class="mt-4 text-primary-100">{{ property.location_name }}</p>
      <div class="mt-7 flex flex-wrap gap-8"><div><span class="text-sm text-primary-200">Starting from</span><strong class="block text-3xl">{{ shortMoney(property.price_from) }}</strong></div><div><span class="text-sm text-primary-200">Initial Deposit</span><strong class="block text-3xl">{{ shortMoney(property.initial_deposit) }}</strong></div></div>
      <div class="mt-8 flex flex-wrap gap-3"><NuxtLink :to="inspectionUrl" class="btn-secondary text-white" @click="track('inspection_started')">Book Site Inspection</NuxtLink><a :href="genericWhatsApp" target="_blank" rel="noopener" class="btn-whatsapp" @click="track('whatsapp_click')">Chat on WhatsApp</a><a :href="phoneLink" class="btn-call" @click="track('phone_click')">Call Lexshield</a></div>
    </div></section>
    <PropertyVideoEnquiry :key="property.id" :property="property" :inspection-url="inspectionUrl" />
    <PropertyMediaGallery v-if="galleryImages.length" :items="galleryImages" :property-name="property.name" />
    <section class="section"><div class="container-page"><h2 class="text-3xl text-neutral-900">Choose Your Plot</h2>
      <div class="mt-7 grid gap-5 lg:grid-cols-3"><article v-for="option in options" :key="option.id" class="card p-6"><p class="text-sm font-semibold uppercase text-primary-700">{{ option.plot_type }}</p><h3 class="mt-2 text-2xl">{{ option.label }}</h3><p class="mt-4 text-3xl font-extrabold text-primary-800">{{ shortMoney(option.outright_price) }} <span class="text-sm font-medium">Starting price</span></p><p class="mt-5 text-sm font-bold">Land Price</p><ul class="mt-2 divide-y text-sm"><li v-for="plan in sortedPlans(option)" :key="plan.id" class="flex justify-between gap-3 py-2"><button class="text-left hover:text-primary-700" @click="trackPlan(option, plan)">{{ plan.label }}</button><strong>{{ shortMoney(plan.price) }}</strong></li></ul><p v-if="property.initial_deposit" class="mt-4 text-sm font-semibold">Initial Deposit: {{ shortMoney(property.initial_deposit) }}</p><a :href="plotWhatsApp(option)" target="_blank" rel="noopener" class="btn-whatsapp mt-5 w-full px-3" @click="selectOption(option)">Enquire About {{ option.label }}</a></article></div>
      <div v-if="hasInteractivePlans" class="mt-10 rounded-2xl bg-primary-900 p-6 text-white"><h2 class="text-2xl">Build Your Payment Option</h2><div class="mt-5 grid gap-4 sm:grid-cols-2"><div><label class="label text-primary-100">Plot Type</label><select v-model="selectedOptionId" class="input"><option v-for="option in options" :key="option.id" :value="option.id">{{ option.label }}</option></select></div><div><label class="label text-primary-100">Payment Option</label><select v-model="selectedPlanId" class="input"><option v-for="plan in selectedOptionPlans" :key="plan.id" :value="plan.id">{{ plan.label }}</option></select></div></div><div v-if="selectedPlan" class="mt-6"><p class="text-sm text-primary-200">Selected price</p><p class="mt-1 text-4xl font-extrabold">{{ fullMoney(selectedPlan.price) }}</p><p v-if="property.pricing_model==='all_inclusive'" class="mt-2 font-semibold text-secondary-300">All-Inclusive Price</p><div class="mt-5 flex flex-wrap gap-3"><a :href="selectedPlanWhatsApp" target="_blank" rel="noopener" class="btn-whatsapp" @click="trackSelectedPlan">Enquire About This Plan</a><NuxtLink :to="selectedInspectionUrl" class="btn-secondary" @click="track('inspection_started',selectedOption)">Book Site Inspection</NuxtLink></div></div></div>
      <div class="mt-6 rounded-xl bg-primary-50 p-5 font-semibold text-primary-900"><p>Initial Deposit: {{ fullMoney(property.initial_deposit) }}</p><p v-if="property.price_inclusive_text" class="mt-1">{{ property.price_inclusive_text }}</p></div>
      <div v-if="statutoryFees.length" class="mt-10 rounded-xl border-2 border-secondary-400 bg-secondary-50 p-6"><h2 class="text-2xl text-neutral-900">Statutory Fees</h2><p class="mt-2 font-semibold text-neutral-800">These statutory fees are separate from the advertised land prices above.</p><div class="mt-5 overflow-x-auto"><table class="w-full text-left"><thead><tr class="border-b"><th class="py-3">Payment Period</th><th class="py-3 text-right">Statutory Fee</th></tr></thead><tbody><tr v-for="fee in statutoryFees" :key="fee.id" class="border-b border-secondary-200"><td class="py-3">{{ fee.label }}</td><td class="py-3 text-right font-bold">{{ shortMoney(fee.amount) }}</td></tr></tbody></table></div></div>
      <div v-if="amenities.length" class="mt-10"><h2 class="text-3xl">Advertised Estate Features</h2><p class="mt-2 text-neutral-600">These are advertised features; their current development status should be confirmed during your enquiry or inspection.</p><ul class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><li v-for="amenity in amenities" :key="amenity.id" class="card flex items-center justify-between p-4"><span class="font-semibold">{{ amenity.name }}</span><span class="badge-primary">{{ amenity.development_status.replace('_',' ') }}</span></li></ul></div>
    </div></section>
    <section class="section bg-neutral-100"><div class="container-page max-w-4xl prose-content"><h2>{{ property.name }}, {{ property.city }}</h2><p>{{ property.description }}</p><h2>Available Plot Sizes</h2><p>{{ optionSentence }}</p><h2>{{ property.name }} Payment Plan</h2><p>Available payment periods and their current land prices are shown above. Pricing varies by plot size and duration.</p><template v-if="property.initial_deposit"><h2>Initial Deposit</h2><p>The stated initial deposit is {{ fullMoney(property.initial_deposit) }}. This is not represented as the total acquisition cost.</p></template><h2>Property Documentation</h2><p v-if="property.documentation?.length">Please review the listed documentation with Lexshield before purchase.</p><p v-else>No verified land-title information has been published for this property yet. Contact Lexshield for current documentation.</p><h2>Book a Site Inspection</h2><p>Visit the property and speak with Lexshield before making your decision.</p><NuxtLink :to="inspectionUrl" class="btn-primary no-underline">Book Site Inspection</NuxtLink><p class="mt-8"><NuxtLink :to="locationUrl">Other Properties in {{ property.city }}</NuxtLink></p></div></section>
    <section v-if="relatedProperties?.length" class="section"><div class="container-page"><h2 class="text-3xl">Other Properties in {{ property.city }}</h2><div class="mt-7 grid gap-6 md:grid-cols-2 lg:grid-cols-3"><PropertyCard v-for="related in relatedProperties" :key="related.id" :property="related" /></div></div></section>
  </div><div v-else-if="!pending" class="container-page py-20"><h1>Property not found</h1></div>
</template>
<script setup lang="ts">
import type { PropertyPaymentPlan, PropertyPlotOption } from '~/types/database'
const route=useRoute(); const {getBySlug,list}=useProperties(); const {data:property,pending}=useAsyncData(`property-${route.params.slug}`,()=>getBySlug(String(route.params.slug))); const {data:relatedProperties}=useAsyncData(`related-${route.params.slug}`,async()=>{const current=await getBySlug(String(route.params.slug));if(!current?.city)return[];return (await list({city:current.city})).filter(item=>item.id!==current.id).slice(0,3)})
const {buildUrl,buildPlotUrl,buildPlanUrl}=useWhatsApp(); const {buildTelLink}=usePhone(); const options=computed(()=>[...(property.value?.property_plot_options||[])].sort((a,b)=>a.sort_order-b.sort_order)); const statutoryFees=computed(()=>[...(property.value?.property_statutory_fees||[])].sort((a,b)=>a.sort_order-b.sort_order)); const amenities=computed(()=>[...(property.value?.property_amenities||[])].sort((a,b)=>a.sort_order-b.sort_order)); const genericWhatsApp=computed(()=>property.value?buildUrl(property.value):'#'); const phoneLink=computed(()=>buildTelLink()); const inspectionUrl=computed(()=>`/book-inspection?property=${property.value?.slug||''}&location=${property.value?.city||''}`); const locationUrl=computed(()=>property.value?.location_name.toLowerCase().includes('apete')?'/properties/apete-ibadan':property.value?.city==='Mowe-Ofada'?'/properties/mowe-ofada':`/properties/${property.value?.city?.toLowerCase().replace(/\s+/g,'-')||''}`); const pageHeading=computed(()=>property.value?.slug==='country-home-estate-iddo-ibadan'?'Country Home Estate — Land for Sale in Iddo, Ibadan':property.value?.slug==='lushville-estate-lamini-apete-ibadan'?'Lushville Estate — Land for Sale in Apete, Ibadan':`${property.value?.name} — Land for Sale in ${property.value?.city}`); const optionSentence=computed(()=>`This estate currently offers ${options.value.map(o=>o.label).join(', ')} plot options.`)
const galleryImages=computed(()=>(property.value?.property_images||[]).filter(item=>item.media_type!=='marketing_video'&&!/\.(mp4|webm|mov)(\?|$)/i.test(item.image_url)))
const selectedOptionId=ref('');const selectedPlanId=ref('');const selectedOption=computed(()=>options.value.find(o=>o.id===selectedOptionId.value));const selectedOptionPlans=computed(()=>selectedOption.value?sortedPlans(selectedOption.value):[]);const selectedPlan=computed(()=>selectedOptionPlans.value.find(p=>p.id===selectedPlanId.value));const hasInteractivePlans=computed(()=>options.value.some(o=>(o.property_payment_plans?.length||0)>0));const selectedPlanWhatsApp=computed(()=>property.value&&selectedOption.value&&selectedPlan.value?buildPlanUrl(property.value,selectedOption.value,selectedPlan.value):'#');const selectedInspectionUrl=computed(()=>`${inspectionUrl.value}&plot=${selectedOption.value?.id||''}&plan=${selectedPlan.value?.id||''}`)
const sortedPlans=(option:PropertyPlotOption)=>[...(option.property_payment_plans||[])].sort((a,b)=>a.sort_order-b.sort_order); const plotWhatsApp=(option:PropertyPlotOption)=>property.value?buildPlotUrl(property.value,option):'#'; const shortMoney=(value:number|null)=>value?`₦${Number((value/1000000).toFixed(2))}M`:'Contact us'; const fullMoney=(value:number|null)=>value?new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(value):''
function track(event:string,option?:PropertyPlotOption){if(import.meta.client)window.dataLayer?.push({event,property_name:property.value?.name,location:property.value?.location_name,plot_option:option?.enquiry_key})} function selectOption(option:PropertyPlotOption){track('plot_option_selected',option);track('whatsapp_click',option)}
function trackPlan(option:PropertyPlotOption,plan:{duration_months:number|null}){if(import.meta.client)window.dataLayer?.push({event:'payment_plan_selected',property_name:property.value?.name,location:property.value?.location_name,plot_option:option.enquiry_key,payment_plan:plan.duration_months===3?'0_3_months':`${plan.duration_months}_months`})}
function trackSelectedPlan(){if(selectedOption.value&&selectedPlan.value){trackPlan(selectedOption.value,selectedPlan.value);track('whatsapp_click',selectedOption.value)}} watch(options,value=>{if(value.length&&!selectedOptionId.value)selectedOptionId.value=value[0].id},{immediate:true});watch(selectedOptionPlans,value=>{selectedPlanId.value=value[0]?.id||''},{immediate:true})
watch(property,value=>{if(value&&import.meta.client)track('property_view')},{immediate:true}); useSeoMeta(()=>({title:property.value?.meta_title||property.value?.name||'Property',description:property.value?.meta_description||property.value?.description||''})); useHead(()=>property.value?{script:[{type:'application/ld+json',innerHTML:JSON.stringify({'@context':'https://schema.org','@type':'Product',name:property.value.name,description:property.value.description,offers:{'@type':'Offer',priceCurrency:'NGN',price:property.value.price_from,availability:'https://schema.org/InStock'},areaServed:{'@type':'Place',name:`${property.value.location_name}, ${property.value.state}, ${property.value.country}`}})}]}:{})
</script>
